### ISSUE TITLE
Team[29] Review

### ISSUE THREAD

**Issue by TioluwaB** [parkd-app/park-d#11]
The reviewer's capstone group TA is @tomashetMcMaster.
In section 1, I think it would be very good to go more in depth with how beneficial an app like this would be for companies and managers. You could add how they would able to gain information if more parking spots are required or the times a company is most busy which could help make more efficient work schedules.

**Comment by almen-ng** [comment]
Thank you for the suggestion! We have made the requisite updated in this PR - https://github.com/parkd-app/park-d/pull/120. Closing this issue.
