### ISSUE TITLE
Team 23 VnV Plan Review: Content-Section Mismatch

### ISSUE THREAD

**Issue by LemonU-mcmaster** [parkd-app/park-d#22]
Section 4.3 Design Verification Plan should focus on spcifying the plan for verifying the on-paper design, that is, the MIS. The provided writing for the section is more about the testing areas in dynamic system testing, and not so much about verifying the quality of MIS.

cc marking TA for group 23 @samm82

**Comment by albertzevanescent** [comment]
Closing this issue.
