### ISSUE TITLE
Team[29] Review

### ISSUE THREAD

**Issue by stoh1729** [parkd-app/park-d#5]
The reviewer's capstone group TA is @tomashetMcMaster.
From "Implementation Environment of the Current System", specific technologies such as HTML, Python 3.7, etc. are listed that the group plans to use to implement the project. This describes the aspect of "how" the project will be implemented. Instead, writing about "what" the system will accomplish can help the SRS document stay abstract.

**Comment by GaryGong27** [comment]
Thank you for your comment
