### ISSUE TITLE
Get Footage for Demo

### ISSUE THREAD

**Issue by JAYapeter** [parkd-app/park-d#51]
Record footage of parking lot with cars going in and out of parking spots. Record one small one (~10 spots) and one big one (~20 spots). Thinking of recording at nearby parking lots.

**Comment by JAYapeter** [comment]
Got footage for two separate parking lots at two different angles for each.

Parking Lot A
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/20882812/215577783-a84c67e4-fe1c-43fe-ab7b-20aef5d9c00a.png">
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/20882812/215578322-0e730496-7593-4799-ba21-98462298473d.png">

Parking Lot B
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/20882812/215578483-5b4bbfc0-e326-4b71-9ee0-36dd313b53c9.png">
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/20882812/215578606-5d4e5f74-9b71-407e-8fc3-c53f0c25f665.png">

**Comment by almen-ng** [comment]
lgtm - closing
