### ISSUE TITLE
Team 22 Design Review: Exported Access Routines in User Action Handler unused

### ISSUE THREAD

**Issue by RutheniumVI** [parkd-app/park-d#59]
The `User Action Handler` module has 5 exported access programs that are never used anywhere else. This means, that either the modules that is going to use these functions is missing or these functions do not need to be exported. Since, this module is the most top level module, I am guessing there is no other module that is going to use these functions. If it is the case that these functions are triggered by some user action, they needed to be documented by using environment variables. eg. `handleAuth` would be triggered by a login button using input from the form where login button & form would be an environment variable.

**Comment by albertzevanescent** [comment]
Closing this issue.
