### ISSUE TITLE
Team[29] Review

### ISSUE THREAD

**Issue by stoh1729** [parkd-app/park-d#6]
The reviewer's capstone group TA is @tomashetMcMaster.
From "Functional Requirements", FR21 ("The system shall non-intrusively prompt the driver...") sounds difficult to easily verify if a prompt is intrusive. It may help to add a qualifier that your group determines to be intrusive to make requirement verification efforts for FR21 easier.

**Comment by almen-ng** [comment]
Thanks for the review! We actually ended up moving this to be implemented in a future revision. We have put this in a backlog for the future and will definitely add a qualifier for it. Closing the issue for now.
