### ISSUE TITLE
Team 22 Design Review: MIS doesn't indicate interaction with the Database

### ISSUE THREAD

**Issue by KevinRK29** [parkd-app/park-d#60]
In the Module Guide, there are modules like Authentication Module that specify the comparison of User information which has to be retrieved from the database but the MIS doesn't show where it is interacting with the database to retrieve this information. 

Furthermore, in the Module Guide, modules like User and Vehicle, it discusses about User and Vehicle data that will be stored into the database, however the MIS doesn't reveal what access routines are being used to store these data.

**Comment by albertzevanescent** [comment]
Closing this issue.
