### ISSUE TITLE
Admin View - Analytics Side Menu UI

### ISSUE THREAD

**Issue by almen-ng** [parkd-app/park-d#68]
Work:
- Give Analytics its own window
- Add cards for standard, accessibility and reserved parking
- Added location name and address

Hint: install bootstrap, react-bootstrap

**Comment by Kabishan** [comment]
Work comments per bullet
- Giving analytics its own window before positioning all of the elements on the webpage is not possible because elements are being thrown off the page (need a separate PR to fix this)
- Cards added (colours dissimilar to that on Figma, but still looks good
- Done

**Comment by Kabishan** [comment]
#71 merged. Closing this issue.
