### ISSUE TITLE
Team[29] Review

### ISSUE THREAD

**Issue by ahmed-nazir** [parkd-app/park-d#7]
The reviewer's capstone group TA is @tomashetMcMaster.
In section 5 where the requirements are listed, most of the content is there. I think it would be beneficial to include requirements that are likely to change as well for items that aren't fully flushed out yet. For example in section 4.3.7 "The system shall support PARKING_LOTS parking areas within six months" this requirement might change.

**Comment by albertzevanescent** [comment]
Closing this issue.
