### ISSUE TITLE
Team 21 VnV Report Review: Lack of details in some test cases and many cases not tested

### ISSUE THREAD

**Issue by snusselder** [parkd-app/park-d#85]
I noticed that most of the test cases didn't go into details on how the test was to be preformed. Test Id BE6-FR16-T1 tests the apps ability to update the directions as the driver commutes to the parking space. How often are these directions updated? I understand not wanting to test cases that would fail because the features haven't been implemented, but I would be worried since there is less than 3 weeks left to complete the project and there are still many functional and non-functional requirement test cases that weren't tested. The VnV Report was the time to test all the features of the project as it should be nearly completed.

**Comment by albertzevanescent** [comment]
Closing this issue.
