### ISSUE TITLE
Team 31 - VnV Report Feedback

### ISSUE THREAD

**Issue by chrisandrade716** [parkd-app/park-d#89]
The report is organized well and quite legible. There are many test cases for all the different of types of requirements which show great coverage. Additionally, it seems the team made beneficial changes since the VnV Plan, and has put honest effort into testing.  I liked that your team decided to make a distinction between "FAIL" and "NOT TESTED" for test cases not yet implemented.

Although the functional and non-functional requirements are straightforward, I think the given unit tests aren't exactly "unit" (there seems to be much more going on in the background during the execution of these unit tests). If I am mistaken, I think these test case tables could benefit from a "Description" column to explain more what is occurring between the "User Action" and "Expected/Actual Value", to clarify that.

Similarly, I think the "User Action" of some of these test cases (more for the FRs and NFRs), are a bit bloated/doing multiple things, and I think if you alternatively didn't want to go for a "Description" column, you could break up these user actions into more specific, verifiable, actions.

Lastly, the choice of "ParMan" as an existing implementation to compare to may have not been the best choice, since you were not really able to access much of their implementation, except through YouTube videos. Although I understand this decision if there weren't many other polished products out there to use.

**Comment by albertzevanescent** [comment]
Closing this issue.
