### ISSUE TITLE
Team31 VnV Report Review: Missing variable names and descriptions in section 2 table

### ISSUE THREAD

**Issue by atunney** [parkd-app/park-d#90]
While reading through the test cases, I noticed there were some variable names that were not present the section 2 Symbols, Abbreviations, and Acronyms table: EXPLORATION_TIME, MAX_TAPS, and MIN_FRAMERATE; while DEFAULT_DELAY was the only one present in the table with a description. As a reader of the VnV report without much context of the system as a whole, it would be beneficial to add these missing variables to the table along with descriptions so the reader doesn't incorrectly infer what they mean and potentially misunderstand what is being tested.

**Comment by albertzevanescent** [comment]
Closing this issue.
