### ISSUE TITLE
Team31 VnV Report Review: More specific tests

### ISSUE THREAD

**Issue by Zhu-K** [parkd-app/park-d#92]
Overall well written and easy to read. Some tests appear little too generic (lacking verifiability) and could use either more specific descriptions (e.g. expected value) or be broken down into more specific test cases.

For example, NFR-LF1-T1 describes verification by "accessing all features they possibly can". Without a list of specific features to access and test, it leaves the results subject to different interpretation especially in the case of user testing. For instance, what counts as all features? How can you be sure that no features were left out of testing?

Providing more specific test cases improves verifiability and reproducibility of the tests and results.

**Comment by albertzevanescent** [comment]
Closing this issue.
