### ISSUE TITLE
Team 31 VnV Report Review

### ISSUE THREAD

**Issue by collinkan** [parkd-app/park-d#93]
Overall, the VnV Report is well structured and easy to follow, and the explanation in section 5 was well written and justified your testing methods.. However, there are a few areas that could be improved by adding in more details or information. One area is the 'Driver Action' column. There a few tests where an admin is performing the test rather than the driver, so the naming for the column isn't entirely accurate. There are also many tests that only involve the backend with no user or admin input required, but there are no specifics in regards to what the system is doing. Also, I feel like for entries that have a results of 'Not Tested' should have N/A for actual value (maybe also expected value).

**Comment by albertzevanescent** [comment]
Closing this issue.
