### ISSUE TITLE
Team 31 VnV Report Review: Tests for behavior in abnormal states

### ISSUE THREAD

**Issue by EthanVinceBudan** [parkd-app/park-d#94]
The majority of currently included test cases are focused on handling user actions, but considering that much of the functionality of Park'd depends on connections between services, it may be useful to ensure that the individual components are somewhat fail-safe when connection problems occur, or when communication fails (especially the user-facing components). Here are some examples of potential situations which _could_ occur and probably should be tested:
 - User's request to navigate times out
 - Parking space usage data is out of date
 - User's location hasn't been updated for a while
 - Admin changes details of spot that user is navigating to
 - Multiple users attempt to navigate to the same parking spot

Of course there may be more to check here.
Well done overall!👏

**Comment by albertzevanescent** [comment]
Closing this issue.
